variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: clone

stages:
  - buildAndDeployUnstableWindows
  - buildAndDeployUnstableAll

buildAndDeployUnstableWindows:
  stage: buildAndDeployUnstableWindows
  tags:
    - WindowsBuilder
  only:
    - tags
  except:
    - ^(dev)
  script:
    - dir
    - Write-Host $CI_COMMIT_TAG
    - bash deploy_windows.sh $CI_COMMIT_TAG $UPDATER_SERVER
  artifacts:
    paths:
      - Grayjay.Desktop.CEF/bin/Release/net8.0/win-x64/Grayjay.Desktop-win-x64-v$CI_COMMIT_TAG.zip
    expire_in: 1d
  when: manual

buildAndDeployUnstableAll:
  stage: buildAndDeployUnstableAll
  tags:
    - LinuxBuilder
  only:
    - tags
  except:
    - ^(dev)
  script:
    - bash deploy.sh $CI_COMMIT_TAG $UPDATER_SERVER
  artifacts:
    paths:
      - /builds/videostreaming/Grayjay.Desktop/Grayjay.Desktop.CEF/bin/Release/net8.0/linux-x64/Grayjay.Desktop-linux-x64-v$CI_COMMIT_TAG.zip
      - /builds/videostreaming/Grayjay.Desktop/Grayjay.Desktop.CEF/bin/Release/net8.0/win-x64/Grayjay.Desktop-win-x64-v$CI_COMMIT_TAG.zip
      - /builds/videostreaming/Grayjay.Desktop/Grayjay.Desktop.CEF/bin/Release/net8.0/osx-arm64/Grayjay.Desktop-osx-arm64-v$CI_COMMIT_TAG.zip
      - /builds/videostreaming/Grayjay.Desktop/Grayjay.Desktop.CEF/bin/Release/net8.0/osx-arm64/Grayjay.Desktop-osx-x64-v$CI_COMMIT_TAG.zip
    expire_in: 1d
  when: manual