name: dotnet package

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive
    
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3

      - name: Display dotnet version
        run: dotnet --version

      - name: Start build
        run: |
          ls
          cd Grayjay.Desktop.CEF
          ls
          dotnet publish -r ios -c Release
          ls
      - name: Zip Artifact
        run: zip -r file.zip /Users/runner/work/Grayjay.Desktop/Grayjay.Desktop/Grayjay.Desktop.CEF/bin/Release/
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          path: file.zip
